export const routes = {
   HOME: '/',
   REGISTRATION: '/registration',
   LOGIN: '/login',
   PROFILE: '/profile/:id',
   ANIME_LIST: '/anime-list',
   ANIME_PAGE: '/anime/:id',
   TOP_ANIME: '/top-anime',
   USER_POLICY: '/users-policy',
   NOTIFICATIONS: '/notifications',
   USER_SETTINGS_ACCOUNT: '/user-settings/:id/account',
   USER_SETTINGS_SITE: '/user-settings/:id/site',
   USER_SETTINGS_SECURITY: '/user-settings/:id/security',
   USER_SETTINGS_PREMIUM: '/user-settings/:id/premium',
}